### ISSUE TITLE
What is the difference between joern and codyze

### ISSUE THREAD

**Issue by tuhaolam** [Fraunhofer-AISEC/codyze#332]
[joern](https://github.com/joernio/joern) is another nice SAST tool, do you compare with it?

**Comment by fwendland** [comment]
Hi @tuhaolam 

Thank you for your question. I'm not sure whether your question isn't better asked and answered as a discussion thread. Maybe we're moving over, if this one is getting to long.

Back in the day, when we started Codyze, we already knew about joern. Back then, however, we felt like something is missing or not working as we required. We started our own Codyze / CPG project that builds on the same ideas as joern. In fact, we were heavily influenced by the research of Fabian Yamaguchi and his papers/PhD thesis.

Since we started Codyze and our CPG project we kind of stopped following joern in detail. Thus, I cannot tell you how they compare nowadays.

One distinction, I believe might still be valid, is that with Codyze we're not necessarily aiming for a classical SAST -- one that finds coding problems (e.g. CWEs). We aim towards compliance of software to requirements frameworks and standards. We want to close the gap between "Your code doesn't seem to have flaws/weaknesses" and "Your code is compliant to fulfill requirements demanded by for instance NIST".

I hope this informal notion partly answers your questions or at least give you some idea. If you want to discuss further I'm happy to move your question over to our discussion board.
