### ISSUE TITLE
Execution via gradlew broken

### ISSUE THREAD

**Issue by m1cm1c** [Fraunhofer-AISEC/codyze#832]
When following the instructions in the readme, `./gradlew run --args="analyze"`  does not work:

```
Type-safe project accessors is an incubating feature.

> Task :codyze-cli:run FAILED
[INFO] [Koin] Started 7 definitions in 0.815337 ms
Usage: codyze-cli [<options>] <command> [<args>]...

Error: no such subcommand analyze

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':codyze-cli:run'.
> Process 'command '/usr/lib/jvm/java-17-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
29 actionable tasks: 7 executed, 22 up-to-date
```

I ran it using Java 17 as seen in the error message (OpenJDK 17.0.10) under Manjaro on the latest commit on master (c61e61ee0776b326c0b3503667d8b9b3e94fd2ea).

This might have failed because the path of the executable has changed but I'm not sure about that. I only know that you state it to be `codyze-cli/build/install/codyze-cli` in the readme even though it actually is `/codyze-cli/build/install/codyze/bin/codyze`.

**Comment by CodingDepot** [comment]
Hi @m1cm1c,
Thanks for creating the issue, it turns out that the README still had outdated information regarding the quickstart.
The problem is that "analyze" is no longer a recognized command.

I've created PR #843 to clear up the confusion in the README.
In summary, the equivalent command in Codyze v3 would be ```./gradlew run --args="--config=config.json runCoko cokoCpg"```, where "runCoko" and "cokoCpg" are the respective subcommands for the `executor` and `backend`. The config file from `codyze-cli/config.json` is then used to set further execution options like the spec files and the code source.

For more information you can refer to the documentation [here](https://www.codyze.io/Codyze/).
